# fly.toml app configuration file generated for coaster-mmo on 2026-08-28T19:17:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coaster-mmo'
primary_region = 'ord'

[build]

[env]
  DB_PATH = '/data/park.db'
  PORT = '8080'

[[mounts]]
  source = 'park_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
